#!/bin/bash

# Define source and destination folders
source_folder="/home/anders/Desktop/emli-final/emli_group_05/mini_project/drone_files/images"
destination_folder="/home/anders/Desktop/emli-final/annotated_metafiles"
model="WildDroneClassifier"

# Synchronize folders based on file names
# First check all files in the source folder
for file in "$source_folder"/*.jpg; do
    filename=$(basename "$file" .jpg)

    # Check whether they exist in the destination folder or not
    if [ ! -e "$destination_folder/$filename.json" ]; then
        # If file does not exist in destination folder, annotate it and add its updated metadata to destination folder
        
        # First annotate the image
        echo "Running $model on the image $filename... (eta 5 min)"
        
        # Define the JSON string as our prompt
        prompt="{\"model\": \"$model\", \"prompt\": \"Describe the animal in this image ./$source_folder/$filename.jpg\", \"format\": \"json\", \"stream\": false}"

        # Use curl to send the JSON data
        answer=$(curl -X POST -H "Content-Type: application/json" -d "$prompt" http://localhost:11434/api/generate)

        # Extract the classification from the response
        classification=$(echo "$answer" | jq -r '.response | fromjson | .classification')

        echo "The image was annotated: $classification"

        # Construct the path to the corresponding JSON file of the image
        json_file="${source_folder}/${filename}.json"

        # Create the new .json with added annotation metadata
        annotated_json_file="${destination_folder}/${filename}.json"

        # Add annotation metadata to the JSON file with model and classification
        # For test metafiles use this:
        #jq --arg model_var "$model" --arg classification_var "$classification" '.[].Annotation = {Model: $model_var, Classification: $classification_var}' "$json_file" > "$annotated_json_file"
        # For actual metafiles use this:
        jq --arg model_var "$model" --arg classification_var "$classification" '.Annotation = {Model: $model_var, Classification: $classification_var}' "$json_file" > "$annotated_json_file"

        echo "Annotation data added to $annotated_json_file"
    fi

done

# Synch with git
echo "Synching with git..."
./emli_group_05/mini_project/drone_files/push_new_metadata.sh
